apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-001001
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    managed-by: backstage
spec:
  project: dev
  
  sources:
    - repoURL: https://github.com/bcocbo/eks_baseline_chart_Helm
      targetRevision: HEAD
      path: .
      helm:
        releaseName: test-001001
        valueFiles:
          - $values/values/dev/test-001001/values.yaml
    - repoURL: https://github.com/bcocbo/gitops-apps
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
